language: c

notifications:
  email: false

before_script:
  # travis has changed to 64-bit and we require 32-bit compatibility libraries 
  - sudo apt-get update 

  # clang
  - "sudo apt-get -qq install gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev || true" 

  # - sudo apt-get -qq install gcc-arm-none-eabi
  - "[ $TOOL_CHAIN = 'sourcery-arm' ] && curl -s https://launchpadlibrarian.net/287101520/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 | sudo tar xjf - -C /opt && export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-5_4-2016q3/bin && /opt/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc --version || true" 

script:
  - scons -C ./

env:
  - TOOL_CHAIN='sourcery-arm' 
