language: c

notifications:
  email: false

git:
  depth: 3

before_script:
  # travis has changed to 64-bit and we require 32-bit compatibility libraries 
  - sudo apt-get update 
  - "sudo apt-get -qq install gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev || true" 
  - "[ $RTT_TOOL_CHAIN = 'sourcery-arm' ] && curl -s https://launchpadlibrarian.net/287101520/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 | sudo tar xjf - -C /opt && export RTT_EXEC_PATH=/opt/gcc-arm-none-eabi-5_4-2016q3/bin && /opt/gcc-arm-none-eabi-5_4-2016q3/bin/arm-none-eabi-gcc --version || true" 

  # 准备RTT BSP用于编译 pwd 当前目录: /home/travis/build/liu2guang/dwin
  - git clone --depth=3 --branch=master https://github.com/RT-Thread/rt-thread.git ../RT-Thread 

  - cp -r /home/travis/build/liu2guang/dwin /home/travis/build/liu2guang/RT-Thread/bsp/packages/dwin
  - ls /home/travis/build/liu2guang/RT-Thread/bsp/packages

install: 
  - true

script:
  - scons -C /home/travis/build/liu2guang/RT-Thread/bsp/imxrt1052-evk/

env:
  - RTT_BSP='imxrt1052-evk' RTT_TOOL_CHAIN='sourcery-arm'
